services:
  app:
    image: ghcr.io/limxingzhi/personal-notion-frontend:latest
    container_name: personal-notion-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NOTION_TOKEN=${NOTION_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
